version: '3.9'

services:
  web-server:
    build:
      context: .
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb-server:27017/cars-db
    volumes: 
      - .:/app

  mongodb-server:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/db_config

volumes:
  mongodb-data:
  mongodb-config:
